//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFiveQ.ExamenUi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using BigFiveQAdmin.Web;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
        
        /// <summary>
        /// Gets a user representing the authenticated identity.
        /// </summary>
        public new User User
        {
            get
            {
                return ((User)(base.User));
            }
        }
    }
}
namespace BigFiveQAdmin.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'AuthenticationService' DomainService.
    /// </summary>
    public sealed partial class AuthenticationContext : global::System.ServiceModel.DomainServices.Client.ApplicationServices.AuthenticationDomainContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class.
        /// </summary>
        public AuthenticationContext() : 
                this(new WebDomainClient<IAuthenticationServiceContract>(new Uri("BigFiveQAdmin-Web-AuthenticationService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The AuthenticationService service URI.</param>
        public AuthenticationContext(Uri serviceUri) : 
                this(new WebDomainClient<IAuthenticationServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public AuthenticationContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="User"/> entity instances that have been loaded into this <see cref="AuthenticationContext"/> instance.
        /// </summary>
        public EntitySet<User> Users
        {
            get
            {
                return base.EntityContainer.GetEntitySet<User>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entity instances using the 'GetUser' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entity instances.</returns>
        public EntityQuery<User> GetUserQuery()
        {
            this.ValidateMethod("GetUserQuery", null);
            return base.CreateQuery<User>("GetUser", null, false, false);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entity instances using the 'Login' query.
        /// </summary>
        /// <param name="userName">The value for the 'userName' parameter of the query.</param>
        /// <param name="password">The value for the 'password' parameter of the query.</param>
        /// <param name="isPersistent">The value for the 'isPersistent' parameter of the query.</param>
        /// <param name="customData">The value for the 'customData' parameter of the query.</param>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entity instances.</returns>
        public EntityQuery<User> LoginQuery(string userName, string password, bool isPersistent, string customData)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("userName", userName);
            parameters.Add("password", password);
            parameters.Add("isPersistent", isPersistent);
            parameters.Add("customData", customData);
            this.ValidateMethod("LoginQuery", parameters);
            return base.CreateQuery<User>("Login", parameters, true, false);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="User"/> entity instances using the 'Logout' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="User"/> entity instances.</returns>
        public EntityQuery<User> LogoutQuery()
        {
            this.ValidateMethod("LogoutQuery", null);
            return base.CreateQuery<User>("Logout", null, true, false);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new AuthenticationContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'AuthenticationService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IAuthenticationServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetUser' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/GetUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/GetUser", ReplyAction="http://tempuri.org/AuthenticationService/GetUserResponse")]
            [WebGet()]
            IAsyncResult BeginGetUser(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetUser'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetUser'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetUser' operation.</returns>
            QueryResult<User> EndGetUser(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'Login' operation.
            /// </summary>
            /// <param name="userName">The value for the 'userName' parameter of this action.</param>
            /// <param name="password">The value for the 'password' parameter of this action.</param>
            /// <param name="isPersistent">The value for the 'isPersistent' parameter of this action.</param>
            /// <param name="customData">The value for the 'customData' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/LoginDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/Login", ReplyAction="http://tempuri.org/AuthenticationService/LoginResponse")]
            IAsyncResult BeginLogin(string userName, string password, bool isPersistent, string customData, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginLogin'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginLogin'.</param>
            /// <returns>The 'QueryResult' returned from the 'Login' operation.</returns>
            QueryResult<User> EndLogin(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'Logout' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/LogoutDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/Logout", ReplyAction="http://tempuri.org/AuthenticationService/LogoutResponse")]
            IAsyncResult BeginLogout(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginLogout'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginLogout'.</param>
            /// <returns>The 'QueryResult' returned from the 'Logout' operation.</returns>
            QueryResult<User> EndLogout(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationService/SubmitChanges", ReplyAction="http://tempuri.org/AuthenticationService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class AuthenticationContextEntityContainer : EntityContainer
        {
            
            public AuthenticationContextEntityContainer()
            {
                this.CreateEntitySet<User>(EntitySetOperations.Edit);
            }
        }
    }
    
    public enum CreateUserStatus
    {
        
        Success = 0,
        
        InvalidUserName = 1,
        
        InvalidPassword = 2,
        
        InvalidQuestion = 3,
        
        InvalidAnswer = 4,
        
        InvalidEmail = 5,
        
        DuplicateUserName = 6,
        
        DuplicateEmail = 7,
        
        Failure = 8,
    }
    
    /// <summary>
    /// The 'RegistrationData' class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web")]
    public sealed partial class RegistrationData : ComplexObject
    {
        
        private string _answer;
        
        private string _email;
        
        private string _friendlyName;
        
        private string _question;
        
        private string _userName;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnAnswerChanging(string value);
        partial void OnAnswerChanged();
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        partial void OnFriendlyNameChanging(string value);
        partial void OnFriendlyNameChanged();
        partial void OnQuestionChanging(string value);
        partial void OnQuestionChanged();
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationData"/> class.
        /// </summary>
        public RegistrationData()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Answer' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references a property 'ValidationErrorBadAnswerLength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [StringLengthAttribute(128, ErrorMessageResourceName = "ValidationErrorBadAnswerLength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        [DataMember()]
        [Display(Name="SecurityAnswerLabel", Order=6, ResourceType=typeof(global::BigFiveQAdmin.Web.Resources.RegistrationDataResources))]
        public string Answer
        {
            get
            {
                return this._answer;
            }
            set
            {
                if ((this._answer != value))
                {
                    this.OnAnswerChanging(value);
                    this.RaiseDataMemberChanging("Answer");
                    this.ValidateProperty("Answer", value);
                    this._answer = value;
                    this.RaiseDataMemberChanged("Answer");
                    this.OnAnswerChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Email' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references a property 'ValidationErrorInvalidEmail' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RegularExpressionAttribute("^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessageResourceName = "ValidationErrorInvalidEmail", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        [DataMember()]
        [Display(Name="EmailLabel", Order=2, ResourceType=typeof(global::BigFiveQAdmin.Web.Resources.RegistrationDataResources))]
        public string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                if ((this._email != value))
                {
                    this.OnEmailChanging(value);
                    this.RaiseDataMemberChanging("Email");
                    this.ValidateProperty("Email", value);
                    this._email = value;
                    this.RaiseDataMemberChanged("Email");
                    this.OnEmailChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'FriendlyName' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references a property 'ValidationErrorBadFriendlyNameLength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [StringLengthAttribute(255, ErrorMessageResourceName = "ValidationErrorBadFriendlyNameLength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        [DataMember()]
        [Display(Description="FriendlyNameDescription", Name="FriendlyNameLabel", Order=1, ResourceType=typeof(global::BigFiveQAdmin.Web.Resources.RegistrationDataResources))]
        public string FriendlyName
        {
            get
            {
                return this._friendlyName;
            }
            set
            {
                if ((this._friendlyName != value))
                {
                    this.OnFriendlyNameChanging(value);
                    this.RaiseDataMemberChanging("FriendlyName");
                    this.ValidateProperty("FriendlyName", value);
                    this._friendlyName = value;
                    this.RaiseDataMemberChanged("FriendlyName");
                    this.OnFriendlyNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Question' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        [DataMember()]
        [Display(Name="SecurityQuestionLabel", Order=5, ResourceType=typeof(global::BigFiveQAdmin.Web.Resources.RegistrationDataResources))]
        public string Question
        {
            get
            {
                return this._question;
            }
            set
            {
                if ((this._question != value))
                {
                    this.OnQuestionChanging(value);
                    this.RaiseDataMemberChanging("Question");
                    this.ValidateProperty("Question", value);
                    this._question = value;
                    this.RaiseDataMemberChanged("Question");
                    this.OnQuestionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'UserName' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references a property 'ValidationErrorInvalidUserName' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RegularExpressionAttribute("^[a-zA-Z0-9_]*$", ErrorMessageResourceName = "ValidationErrorInvalidUserName", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references a property 'ValidationErrorBadUserNameLength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [StringLengthAttribute(255, ErrorMessageResourceName = "ValidationErrorBadUserNameLength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources), MinimumLength = 4)]
        // 
        [DataMember()]
        [Display(Name="UserNameLabel", Order=0, ResourceType=typeof(global::BigFiveQAdmin.Web.Resources.RegistrationDataResources))]
        public string UserName
        {
            get
            {
                return this._userName;
            }
            set
            {
                if ((this._userName != value))
                {
                    this.OnUserNameChanging(value);
                    this.RaiseDataMemberChanging("UserName");
                    this.ValidateProperty("UserName", value);
                    this._userName = value;
                    this.RaiseDataMemberChanged("UserName");
                    this.OnUserNameChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// The 'User' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web")]
    public sealed partial class User : Entity, global::System.Security.Principal.IIdentity, global::System.Security.Principal.IPrincipal
    {
        
        private string _friendlyName;
        
        private string _name = string.Empty;
        
        private IEnumerable<string> _roles;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnFriendlyNameChanging(string value);
        partial void OnFriendlyNameChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnRolesChanging(IEnumerable<string> value);
        partial void OnRolesChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'FriendlyName' value.
        /// </summary>
        [DataMember()]
        public string FriendlyName
        {
            get
            {
                return this._friendlyName;
            }
            set
            {
                if ((this._friendlyName != value))
                {
                    this.OnFriendlyNameChanging(value);
                    this.RaiseDataMemberChanging("FriendlyName");
                    this.ValidateProperty("FriendlyName", value);
                    this._friendlyName = value;
                    this.RaiseDataMemberChanged("FriendlyName");
                    this.OnFriendlyNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Name' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaisePropertyChanged("Name");
                    this.OnNameChanged();
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Roles' value.
        /// </summary>
        [DataMember()]
        [Editable(false)]
        public IEnumerable<string> Roles
        {
            get
            {
                return this._roles;
            }
            set
            {
                if ((this._roles != value))
                {
                    this.OnRolesChanging(value);
                    this.ValidateProperty("Roles", value);
                    this._roles = value;
                    this.RaisePropertyChanged("Roles");
                    this.OnRolesChanged();
                }
            }
        }
        
        string global::System.Security.Principal.IIdentity.AuthenticationType
        {
            get
            {
                return string.Empty;
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the identity is authenticated.
        /// </summary>
        /// <remarks>
        /// This value is <c>true</c> if <see cref="Name"/> is not <c>null</c> or empty.
        /// </remarks>
        public bool IsAuthenticated
        {
            get
            {
                return (true != string.IsNullOrEmpty(this.Name));
            }
        }
        
        string global::System.Security.Principal.IIdentity.Name
        {
            get
            {
                return this.Name;
            }
        }
        
        global::System.Security.Principal.IIdentity global::System.Security.Principal.IPrincipal.Identity
        {
            get
            {
                return this;
            }
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._name;
        }
        
        /// <summary>
        /// Return whether the principal is in the role.
        /// </summary>
        /// <remarks>
        /// Returns whether the specified role is contained in the roles.
        /// This implementation is case sensitive.
        /// </remarks>
        /// <param name="role">The name of the role for which to check membership.</param>
        /// <returns>Whether the principal is in the role.</returns>
        public bool IsInRole(string role)
        {
            if ((this.Roles == null))
            {
                return false;
            }
            return global::System.Linq.Enumerable.Contains(this.Roles, role);
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'UserRegistrationService' DomainService.
    /// </summary>
    public sealed partial class UserRegistrationContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRegistrationContext"/> class.
        /// </summary>
        public UserRegistrationContext() : 
                this(new WebDomainClient<IUserRegistrationServiceContract>(new Uri("BigFiveQAdmin-Web-UserRegistrationService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRegistrationContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The UserRegistrationService service URI.</param>
        public UserRegistrationContext(Uri serviceUri) : 
                this(new WebDomainClient<IUserRegistrationServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRegistrationContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public UserRegistrationContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Asynchronously invokes the 'CreateUser' method of the DomainService.
        /// </summary>
        /// <param name="user">The value for the 'user' parameter of this action.</param>
        /// <param name="password">The value for the 'password' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        // Unable to generate the following attributes for parameter 'password' due to the following errors:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references a property 'ValidationErrorBadPasswordStrength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RegularExpressionAttribute("^.*[^a-zA-Z0-9].*$", ErrorMessageResourceName = "ValidationErrorBadPasswordStrength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references a property 'ValidationErrorBadPasswordLength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [StringLengthAttribute(50, ErrorMessageResourceName = "ValidationErrorBadPasswordLength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources), MinimumLength = 7)]
        // 
        public InvokeOperation<CreateUserStatus> CreateUser(RegistrationData user, string password, Action<InvokeOperation<CreateUserStatus>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("user", user);
            parameters.Add("password", password);
            this.ValidateMethod("CreateUser", parameters);
            return ((InvokeOperation<CreateUserStatus>)(this.InvokeOperation("CreateUser", typeof(CreateUserStatus), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'CreateUser' method of the DomainService.
        /// </summary>
        /// <param name="user">The value for the 'user' parameter of this action.</param>
        /// <param name="password">The value for the 'password' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        // Unable to generate the following attributes for parameter 'password' due to the following errors:
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' references a property 'ValidationErrorBadPasswordStrength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RegularExpressionAttribute("^.*[^a-zA-Z0-9].*$", ErrorMessageResourceName = "ValidationErrorBadPasswordStrength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' references a property 'ValidationErrorRequiredField' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [RequiredAttribute(ErrorMessageResourceName = "ValidationErrorRequiredField", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources))]
        // 
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'. If you would like the attribute to be generated, make sure the assembly containing the attribute is referenced on the client.
        // - The attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' references a property 'ValidationErrorBadPasswordLength' on type 'BigFiveQAdmin.Web.Resources.ValidationErrorResources' that is not accessible in the client project 'BigFiveQ.ExamenUi'.
        // [StringLengthAttribute(50, ErrorMessageResourceName = "ValidationErrorBadPasswordLength", ErrorMessageResourceType = typeof(BigFiveQAdmin.Web.Resources.ValidationErrorResources), MinimumLength = 7)]
        // 
        public InvokeOperation<CreateUserStatus> CreateUser(RegistrationData user, string password)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("user", user);
            parameters.Add("password", password);
            this.ValidateMethod("CreateUser", parameters);
            return ((InvokeOperation<CreateUserStatus>)(this.InvokeOperation("CreateUser", typeof(CreateUserStatus), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new UserRegistrationContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'UserRegistrationService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IUserRegistrationServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'CreateUser' operation.
            /// </summary>
            /// <param name="user">The value for the 'user' parameter of this action.</param>
            /// <param name="password">The value for the 'password' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/UserRegistrationService/CreateUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/UserRegistrationService/CreateUser", ReplyAction="http://tempuri.org/UserRegistrationService/CreateUserResponse")]
            IAsyncResult BeginCreateUser(RegistrationData user, string password, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginCreateUser'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginCreateUser'.</param>
            /// <returns>The 'CreateUserStatus' returned from the 'CreateUser' operation.</returns>
            CreateUserStatus EndCreateUser(IAsyncResult result);
        }
        
        internal sealed class UserRegistrationContextEntityContainer : EntityContainer
        {
            
            public UserRegistrationContextEntityContainer()
            {
            }
        }
    }
}
namespace BigFiveQAdmin.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// The 'EvaluacionBigFive' entity class.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Models")]
    public sealed partial class EvaluacionBigFive : Entity
    {
        
        private Nullable<int> _afabilidad;
        
        private Nullable<int> _aperturaCultura;
        
        private Nullable<int> _aperturaExperiencia;
        
        private Nullable<int> _aperturaMental;
        
        private Nullable<int> _controlEmociones;
        
        private Nullable<int> _controlImpulsos;
        
        private Nullable<int> _cooperacion;
        
        private Nullable<int> _cordialidad;
        
        private Nullable<int> _dinamismo;
        
        private Nullable<int> _distorsion;
        
        private Nullable<int> _dominancia;
        
        private Nullable<int> _energia;
        
        private Nullable<int> _escrupolosidad;
        
        private Nullable<int> _estabilidadEmocional;
        
        private Nullable<DateTime> _fechaRealizacion;
        
        private int _id;
        
        private Nullable<int> _idPersona;
        
        private string _nombreExamen;
        
        private Nullable<int> _numeroEvaluacion;
        
        private Nullable<int> _perseverancia;
        
        private EntityRef<Persona> _persona;
        
        private Nullable<int> _teson;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnAfabilidadChanging(Nullable<int> value);
        partial void OnAfabilidadChanged();
        partial void OnAperturaCulturaChanging(Nullable<int> value);
        partial void OnAperturaCulturaChanged();
        partial void OnAperturaExperienciaChanging(Nullable<int> value);
        partial void OnAperturaExperienciaChanged();
        partial void OnAperturaMentalChanging(Nullable<int> value);
        partial void OnAperturaMentalChanged();
        partial void OnControlEmocionesChanging(Nullable<int> value);
        partial void OnControlEmocionesChanged();
        partial void OnControlImpulsosChanging(Nullable<int> value);
        partial void OnControlImpulsosChanged();
        partial void OnCooperacionChanging(Nullable<int> value);
        partial void OnCooperacionChanged();
        partial void OnCordialidadChanging(Nullable<int> value);
        partial void OnCordialidadChanged();
        partial void OnDinamismoChanging(Nullable<int> value);
        partial void OnDinamismoChanged();
        partial void OnDistorsionChanging(Nullable<int> value);
        partial void OnDistorsionChanged();
        partial void OnDominanciaChanging(Nullable<int> value);
        partial void OnDominanciaChanged();
        partial void OnEnergiaChanging(Nullable<int> value);
        partial void OnEnergiaChanged();
        partial void OnEscrupolosidadChanging(Nullable<int> value);
        partial void OnEscrupolosidadChanged();
        partial void OnEstabilidadEmocionalChanging(Nullable<int> value);
        partial void OnEstabilidadEmocionalChanged();
        partial void OnFechaRealizacionChanging(Nullable<DateTime> value);
        partial void OnFechaRealizacionChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnIdPersonaChanging(Nullable<int> value);
        partial void OnIdPersonaChanged();
        partial void OnNombreExamenChanging(string value);
        partial void OnNombreExamenChanged();
        partial void OnNumeroEvaluacionChanging(Nullable<int> value);
        partial void OnNumeroEvaluacionChanged();
        partial void OnPerseveranciaChanging(Nullable<int> value);
        partial void OnPerseveranciaChanged();
        partial void OnTesonChanging(Nullable<int> value);
        partial void OnTesonChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluacionBigFive"/> class.
        /// </summary>
        public EvaluacionBigFive()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Afabilidad' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Afabilidad
        {
            get
            {
                return this._afabilidad;
            }
            set
            {
                if ((this._afabilidad != value))
                {
                    this.OnAfabilidadChanging(value);
                    this.RaiseDataMemberChanging("Afabilidad");
                    this.ValidateProperty("Afabilidad", value);
                    this._afabilidad = value;
                    this.RaiseDataMemberChanged("Afabilidad");
                    this.OnAfabilidadChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'AperturaCultura' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> AperturaCultura
        {
            get
            {
                return this._aperturaCultura;
            }
            set
            {
                if ((this._aperturaCultura != value))
                {
                    this.OnAperturaCulturaChanging(value);
                    this.RaiseDataMemberChanging("AperturaCultura");
                    this.ValidateProperty("AperturaCultura", value);
                    this._aperturaCultura = value;
                    this.RaiseDataMemberChanged("AperturaCultura");
                    this.OnAperturaCulturaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'AperturaExperiencia' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> AperturaExperiencia
        {
            get
            {
                return this._aperturaExperiencia;
            }
            set
            {
                if ((this._aperturaExperiencia != value))
                {
                    this.OnAperturaExperienciaChanging(value);
                    this.RaiseDataMemberChanging("AperturaExperiencia");
                    this.ValidateProperty("AperturaExperiencia", value);
                    this._aperturaExperiencia = value;
                    this.RaiseDataMemberChanged("AperturaExperiencia");
                    this.OnAperturaExperienciaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'AperturaMental' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> AperturaMental
        {
            get
            {
                return this._aperturaMental;
            }
            set
            {
                if ((this._aperturaMental != value))
                {
                    this.OnAperturaMentalChanging(value);
                    this.RaiseDataMemberChanging("AperturaMental");
                    this.ValidateProperty("AperturaMental", value);
                    this._aperturaMental = value;
                    this.RaiseDataMemberChanged("AperturaMental");
                    this.OnAperturaMentalChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ControlEmociones' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> ControlEmociones
        {
            get
            {
                return this._controlEmociones;
            }
            set
            {
                if ((this._controlEmociones != value))
                {
                    this.OnControlEmocionesChanging(value);
                    this.RaiseDataMemberChanging("ControlEmociones");
                    this.ValidateProperty("ControlEmociones", value);
                    this._controlEmociones = value;
                    this.RaiseDataMemberChanged("ControlEmociones");
                    this.OnControlEmocionesChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'ControlImpulsos' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> ControlImpulsos
        {
            get
            {
                return this._controlImpulsos;
            }
            set
            {
                if ((this._controlImpulsos != value))
                {
                    this.OnControlImpulsosChanging(value);
                    this.RaiseDataMemberChanging("ControlImpulsos");
                    this.ValidateProperty("ControlImpulsos", value);
                    this._controlImpulsos = value;
                    this.RaiseDataMemberChanged("ControlImpulsos");
                    this.OnControlImpulsosChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Cooperacion' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Cooperacion
        {
            get
            {
                return this._cooperacion;
            }
            set
            {
                if ((this._cooperacion != value))
                {
                    this.OnCooperacionChanging(value);
                    this.RaiseDataMemberChanging("Cooperacion");
                    this.ValidateProperty("Cooperacion", value);
                    this._cooperacion = value;
                    this.RaiseDataMemberChanged("Cooperacion");
                    this.OnCooperacionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Cordialidad' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Cordialidad
        {
            get
            {
                return this._cordialidad;
            }
            set
            {
                if ((this._cordialidad != value))
                {
                    this.OnCordialidadChanging(value);
                    this.RaiseDataMemberChanging("Cordialidad");
                    this.ValidateProperty("Cordialidad", value);
                    this._cordialidad = value;
                    this.RaiseDataMemberChanged("Cordialidad");
                    this.OnCordialidadChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Dinamismo' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Dinamismo
        {
            get
            {
                return this._dinamismo;
            }
            set
            {
                if ((this._dinamismo != value))
                {
                    this.OnDinamismoChanging(value);
                    this.RaiseDataMemberChanging("Dinamismo");
                    this.ValidateProperty("Dinamismo", value);
                    this._dinamismo = value;
                    this.RaiseDataMemberChanged("Dinamismo");
                    this.OnDinamismoChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Distorsion' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Distorsion
        {
            get
            {
                return this._distorsion;
            }
            set
            {
                if ((this._distorsion != value))
                {
                    this.OnDistorsionChanging(value);
                    this.RaiseDataMemberChanging("Distorsion");
                    this.ValidateProperty("Distorsion", value);
                    this._distorsion = value;
                    this.RaiseDataMemberChanged("Distorsion");
                    this.OnDistorsionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Dominancia' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Dominancia
        {
            get
            {
                return this._dominancia;
            }
            set
            {
                if ((this._dominancia != value))
                {
                    this.OnDominanciaChanging(value);
                    this.RaiseDataMemberChanging("Dominancia");
                    this.ValidateProperty("Dominancia", value);
                    this._dominancia = value;
                    this.RaiseDataMemberChanged("Dominancia");
                    this.OnDominanciaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Energia' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Energia
        {
            get
            {
                return this._energia;
            }
            set
            {
                if ((this._energia != value))
                {
                    this.OnEnergiaChanging(value);
                    this.RaiseDataMemberChanging("Energia");
                    this.ValidateProperty("Energia", value);
                    this._energia = value;
                    this.RaiseDataMemberChanged("Energia");
                    this.OnEnergiaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Escrupolosidad' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Escrupolosidad
        {
            get
            {
                return this._escrupolosidad;
            }
            set
            {
                if ((this._escrupolosidad != value))
                {
                    this.OnEscrupolosidadChanging(value);
                    this.RaiseDataMemberChanging("Escrupolosidad");
                    this.ValidateProperty("Escrupolosidad", value);
                    this._escrupolosidad = value;
                    this.RaiseDataMemberChanged("Escrupolosidad");
                    this.OnEscrupolosidadChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'EstabilidadEmocional' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> EstabilidadEmocional
        {
            get
            {
                return this._estabilidadEmocional;
            }
            set
            {
                if ((this._estabilidadEmocional != value))
                {
                    this.OnEstabilidadEmocionalChanging(value);
                    this.RaiseDataMemberChanging("EstabilidadEmocional");
                    this.ValidateProperty("EstabilidadEmocional", value);
                    this._estabilidadEmocional = value;
                    this.RaiseDataMemberChanged("EstabilidadEmocional");
                    this.OnEstabilidadEmocionalChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'FechaRealizacion' value.
        /// </summary>
        [DataMember()]
        public Nullable<DateTime> FechaRealizacion
        {
            get
            {
                return this._fechaRealizacion;
            }
            set
            {
                if ((this._fechaRealizacion != value))
                {
                    this.OnFechaRealizacionChanging(value);
                    this.RaiseDataMemberChanging("FechaRealizacion");
                    this.ValidateProperty("FechaRealizacion", value);
                    this._fechaRealizacion = value;
                    this.RaiseDataMemberChanged("FechaRealizacion");
                    this.OnFechaRealizacionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'IdPersona' value.
        /// </summary>
        [DataMember()]
        [RoundtripOriginal()]
        public Nullable<int> IdPersona
        {
            get
            {
                return this._idPersona;
            }
            set
            {
                if ((this._idPersona != value))
                {
                    this.OnIdPersonaChanging(value);
                    this.RaiseDataMemberChanging("IdPersona");
                    this.ValidateProperty("IdPersona", value);
                    this._idPersona = value;
                    this.RaiseDataMemberChanged("IdPersona");
                    this.OnIdPersonaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'NombreExamen' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(255)]
        public string NombreExamen
        {
            get
            {
                return this._nombreExamen;
            }
            set
            {
                if ((this._nombreExamen != value))
                {
                    this.OnNombreExamenChanging(value);
                    this.RaiseDataMemberChanging("NombreExamen");
                    this.ValidateProperty("NombreExamen", value);
                    this._nombreExamen = value;
                    this.RaiseDataMemberChanged("NombreExamen");
                    this.OnNombreExamenChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'NumeroEvaluacion' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> NumeroEvaluacion
        {
            get
            {
                return this._numeroEvaluacion;
            }
            set
            {
                if ((this._numeroEvaluacion != value))
                {
                    this.OnNumeroEvaluacionChanging(value);
                    this.RaiseDataMemberChanging("NumeroEvaluacion");
                    this.ValidateProperty("NumeroEvaluacion", value);
                    this._numeroEvaluacion = value;
                    this.RaiseDataMemberChanged("NumeroEvaluacion");
                    this.OnNumeroEvaluacionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Perseverancia' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Perseverancia
        {
            get
            {
                return this._perseverancia;
            }
            set
            {
                if ((this._perseverancia != value))
                {
                    this.OnPerseveranciaChanging(value);
                    this.RaiseDataMemberChanging("Perseverancia");
                    this.ValidateProperty("Perseverancia", value);
                    this._perseverancia = value;
                    this.RaiseDataMemberChanged("Perseverancia");
                    this.OnPerseveranciaChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the associated <see cref="Persona"/> entity.
        /// </summary>
        [Association("Persona_EvaluacionBigFive", "IdPersona", "Id", IsForeignKey=true)]
        [XmlIgnore()]
        public Persona Persona
        {
            get
            {
                if ((this._persona == null))
                {
                    this._persona = new EntityRef<Persona>(this, "Persona", this.FilterPersona);
                }
                return this._persona.Entity;
            }
            set
            {
                Persona previous = this.Persona;
                if ((previous != value))
                {
                    this.ValidateProperty("Persona", value);
                    if ((previous != null))
                    {
                        this._persona.Entity = null;
                        previous.EvaluacionBigFives.Remove(this);
                    }
                    if ((value != null))
                    {
                        this.IdPersona = value.Id;
                    }
                    else
                    {
                        this.IdPersona = default(Nullable<int>);
                    }
                    this._persona.Entity = value;
                    if ((value != null))
                    {
                        value.EvaluacionBigFives.Add(this);
                    }
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Teson' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Teson
        {
            get
            {
                return this._teson;
            }
            set
            {
                if ((this._teson != value))
                {
                    this.OnTesonChanging(value);
                    this.RaiseDataMemberChanging("Teson");
                    this.ValidateProperty("Teson", value);
                    this._teson = value;
                    this.RaiseDataMemberChanged("Teson");
                    this.OnTesonChanged();
                }
            }
        }
        
        private bool FilterPersona(Persona entity)
        {
            return (entity.Id == this.IdPersona);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
    
    /// <summary>
    /// The 'Persona' entity class.
    /// This entity is shared between the following contexts:
    /// The <see cref="EvaluacionContext"/> context.
    /// The <see cref="PersonaContext"/> context.
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Models")]
    public sealed partial class Persona : Entity
    {
        
        private string _apellidos;
        
        private Nullable<int> _edad;
        
        private string _email;
        
        private EntityCollection<EvaluacionBigFive> _evaluacionBigFives;
        
        private int _id;
        
        private string _institucion;
        
        private string _nombres;
        
        private string _nombreUsuario;
        
        private string _password;
        
        private string _telefono;
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();
        partial void OnApellidosChanging(string value);
        partial void OnApellidosChanged();
        partial void OnEdadChanging(Nullable<int> value);
        partial void OnEdadChanged();
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnInstitucionChanging(string value);
        partial void OnInstitucionChanged();
        partial void OnNombresChanging(string value);
        partial void OnNombresChanged();
        partial void OnNombreUsuarioChanging(string value);
        partial void OnNombreUsuarioChanged();
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        partial void OnTelefonoChanging(string value);
        partial void OnTelefonoChanged();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Persona"/> class.
        /// </summary>
        public Persona()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets or sets the 'Apellidos' value.
        /// </summary>
        [DataMember()]
        [Required(ErrorMessage="Este campo es requerido")]
        [StringLength(255)]
        public string Apellidos
        {
            get
            {
                return this._apellidos;
            }
            set
            {
                if ((this._apellidos != value))
                {
                    this.OnApellidosChanging(value);
                    this.RaiseDataMemberChanging("Apellidos");
                    this.ValidateProperty("Apellidos", value);
                    this._apellidos = value;
                    this.RaiseDataMemberChanged("Apellidos");
                    this.OnApellidosChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Edad' value.
        /// </summary>
        [DataMember()]
        public Nullable<int> Edad
        {
            get
            {
                return this._edad;
            }
            set
            {
                if ((this._edad != value))
                {
                    this.OnEdadChanging(value);
                    this.RaiseDataMemberChanging("Edad");
                    this.ValidateProperty("Edad", value);
                    this._edad = value;
                    this.RaiseDataMemberChanged("Edad");
                    this.OnEdadChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Email' value.
        /// </summary>
        [DataMember()]
        [RegularExpression("(?<user>[^@]+)@(?<host>.+)")]
        [Required(ErrorMessage="Email es requerido")]
        [StringLength(50)]
        public string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                if ((this._email != value))
                {
                    this.OnEmailChanging(value);
                    this.RaiseDataMemberChanging("Email");
                    this.ValidateProperty("Email", value);
                    this._email = value;
                    this.RaiseDataMemberChanged("Email");
                    this.OnEmailChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets the collection of associated <see cref="EvaluacionBigFive"/> entity instances.
        /// </summary>
        [Association("Persona_EvaluacionBigFive", "Id", "IdPersona")]
        [XmlIgnore()]
        public EntityCollection<EvaluacionBigFive> EvaluacionBigFives
        {
            get
            {
                if ((this._evaluacionBigFives == null))
                {
                    this._evaluacionBigFives = new EntityCollection<EvaluacionBigFive>(this, "EvaluacionBigFives", this.FilterEvaluacionBigFives, this.AttachEvaluacionBigFives, this.DetachEvaluacionBigFives);
                }
                return this._evaluacionBigFives;
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Id' value.
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaisePropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Institucion' value.
        /// </summary>
        [DataMember()]
        [StringLength(255)]
        public string Institucion
        {
            get
            {
                return this._institucion;
            }
            set
            {
                if ((this._institucion != value))
                {
                    this.OnInstitucionChanging(value);
                    this.RaiseDataMemberChanging("Institucion");
                    this.ValidateProperty("Institucion", value);
                    this._institucion = value;
                    this.RaiseDataMemberChanged("Institucion");
                    this.OnInstitucionChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Nombres' value.
        /// </summary>
        [DataMember()]
        [Required()]
        [StringLength(255)]
        public string Nombres
        {
            get
            {
                return this._nombres;
            }
            set
            {
                if ((this._nombres != value))
                {
                    this.OnNombresChanging(value);
                    this.RaiseDataMemberChanging("Nombres");
                    this.ValidateProperty("Nombres", value);
                    this._nombres = value;
                    this.RaiseDataMemberChanged("Nombres");
                    this.OnNombresChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'NombreUsuario' value.
        /// </summary>
        [DataMember()]
        [Required(ErrorMessage="Este campo es requerido")]
        [StringLength(20, ErrorMessage="El Nombre es muy Largo!")]
        public string NombreUsuario
        {
            get
            {
                return this._nombreUsuario;
            }
            set
            {
                if ((this._nombreUsuario != value))
                {
                    this.OnNombreUsuarioChanging(value);
                    this.RaiseDataMemberChanging("NombreUsuario");
                    this.ValidateProperty("NombreUsuario", value);
                    this._nombreUsuario = value;
                    this.RaiseDataMemberChanged("NombreUsuario");
                    this.OnNombreUsuarioChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Password' value.
        /// </summary>
        // The following attributes were not generated:
        // 
        // - The validation attribute 'System.ComponentModel.DataAnnotations.RegularExpressionAttribute' contains ErrorMessageResourceType='<unspecified>' and ErrorMessageResourceName='La contraseña debe tenerr 6 letras numero y carateres como!@#$%^'.  You must specify values for both or neither.
        // [RegularExpressionAttribute("^.*[^a-zA-Z0-9].*$", ErrorMessageResourceName = "La contraseña debe tenerr 6 letras numero y carateres como!@#$%^")]
        // 
        // - The validation attribute 'System.ComponentModel.DataAnnotations.RequiredAttribute' contains ErrorMessageResourceType='<unspecified>' and ErrorMessageResourceName='Debe completar este campo'.  You must specify values for both or neither.
        // [RequiredAttribute(ErrorMessageResourceName = "Debe completar este campo")]
        // 
        // - The validation attribute 'System.ComponentModel.DataAnnotations.StringLengthAttribute' contains ErrorMessageResourceType='<unspecified>' and ErrorMessageResourceName='La contraseña debe tener como minimo 6 carateres'.  You must specify values for both or neither.
        // [StringLengthAttribute(50, ErrorMessageResourceName = "La contraseña debe tener como minimo 6 carateres", MinimumLength = 7)]
        // 
        [DataMember()]
        public string Password
        {
            get
            {
                return this._password;
            }
            set
            {
                if ((this._password != value))
                {
                    this.OnPasswordChanging(value);
                    this.RaiseDataMemberChanging("Password");
                    this.ValidateProperty("Password", value);
                    this._password = value;
                    this.RaiseDataMemberChanged("Password");
                    this.OnPasswordChanged();
                }
            }
        }
        
        /// <summary>
        /// Gets or sets the 'Telefono' value.
        /// </summary>
        [DataMember()]
        [StringLength(255)]
        public string Telefono
        {
            get
            {
                return this._telefono;
            }
            set
            {
                if ((this._telefono != value))
                {
                    this.OnTelefonoChanging(value);
                    this.RaiseDataMemberChanging("Telefono");
                    this.ValidateProperty("Telefono", value);
                    this._telefono = value;
                    this.RaiseDataMemberChanged("Telefono");
                    this.OnTelefonoChanged();
                }
            }
        }
        
        private void AttachEvaluacionBigFives(EvaluacionBigFive entity)
        {
            entity.Persona = this;
        }
        
        private void DetachEvaluacionBigFives(EvaluacionBigFive entity)
        {
            entity.Persona = null;
        }
        
        private bool FilterEvaluacionBigFives(EvaluacionBigFive entity)
        {
            return (entity.IdPersona == this.Id);
        }
        
        /// <summary>
        /// Computes a value from the key fields that uniquely identifies this entity instance.
        /// </summary>
        /// <returns>An object instance that uniquely identifies this entity instance.</returns>
        public override object GetIdentity()
        {
            return this._id;
        }
    }
}
namespace BigFiveQAdmin.Web.Services
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using BigFiveQAdmin.Web.Models;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'EvaluacionService' DomainService.
    /// </summary>
    public sealed partial class EvaluacionContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluacionContext"/> class.
        /// </summary>
        public EvaluacionContext() : 
                this(new WebDomainClient<IEvaluacionServiceContract>(new Uri("BigFiveQAdmin-Web-Services-EvaluacionService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluacionContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The EvaluacionService service URI.</param>
        public EvaluacionContext(Uri serviceUri) : 
                this(new WebDomainClient<IEvaluacionServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluacionContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public EvaluacionContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="EvaluacionBigFive"/> entity instances that have been loaded into this <see cref="EvaluacionContext"/> instance.
        /// </summary>
        public EntitySet<EvaluacionBigFive> EvaluacionBigFives
        {
            get
            {
                return base.EntityContainer.GetEntitySet<EvaluacionBigFive>();
            }
        }
        
        /// <summary>
        /// Gets the set of <see cref="Persona"/> entity instances that have been loaded into this <see cref="EvaluacionContext"/> instance.
        /// </summary>
        public EntitySet<Persona> Personas
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Persona>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="EvaluacionBigFive"/> entity instances using the 'GetEvaluacionBigFives' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="EvaluacionBigFive"/> entity instances.</returns>
        public EntityQuery<EvaluacionBigFive> GetEvaluacionBigFivesQuery()
        {
            this.ValidateMethod("GetEvaluacionBigFivesQuery", null);
            return base.CreateQuery<EvaluacionBigFive>("GetEvaluacionBigFives", null, false, true);
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Persona"/> entity instances using the 'GetPersonas' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Persona"/> entity instances.</returns>
        public EntityQuery<Persona> GetPersonasQuery()
        {
            this.ValidateMethod("GetPersonasQuery", null);
            return base.CreateQuery<Persona>("GetPersonas", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new EvaluacionContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'EvaluacionService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IEvaluacionServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetEvaluacionBigFives' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/EvaluacionService/GetEvaluacionBigFivesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/EvaluacionService/GetEvaluacionBigFives", ReplyAction="http://tempuri.org/EvaluacionService/GetEvaluacionBigFivesResponse")]
            [WebGet()]
            IAsyncResult BeginGetEvaluacionBigFives(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetEvaluacionBigFives'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetEvaluacionBigFives'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetEvaluacionBigFives' operation.</returns>
            QueryResult<EvaluacionBigFive> EndGetEvaluacionBigFives(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonas' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/EvaluacionService/GetPersonasDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/EvaluacionService/GetPersonas", ReplyAction="http://tempuri.org/EvaluacionService/GetPersonasResponse")]
            [WebGet()]
            IAsyncResult BeginGetPersonas(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonas'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonas'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersonas' operation.</returns>
            QueryResult<Persona> EndGetPersonas(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/EvaluacionService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/EvaluacionService/SubmitChanges", ReplyAction="http://tempuri.org/EvaluacionService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class EvaluacionContextEntityContainer : EntityContainer
        {
            
            public EvaluacionContextEntityContainer()
            {
                this.CreateEntitySet<EvaluacionBigFive>(EntitySetOperations.All);
                this.CreateEntitySet<Persona>(EntitySetOperations.All);
            }
        }
    }
    
    /// <summary>
    /// The DomainContext corresponding to the 'PersonaService' DomainService.
    /// </summary>
    public sealed partial class PersonaContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonaContext"/> class.
        /// </summary>
        public PersonaContext() : 
                this(new WebDomainClient<IPersonaServiceContract>(new Uri("BigFiveQAdmin-Web-Services-PersonaService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonaContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The PersonaService service URI.</param>
        public PersonaContext(Uri serviceUri) : 
                this(new WebDomainClient<IPersonaServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonaContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public PersonaContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the set of <see cref="Persona"/> entity instances that have been loaded into this <see cref="PersonaContext"/> instance.
        /// </summary>
        public EntitySet<Persona> Personas
        {
            get
            {
                return base.EntityContainer.GetEntitySet<Persona>();
            }
        }
        
        /// <summary>
        /// Gets an EntityQuery instance that can be used to load <see cref="Persona"/> entity instances using the 'GetPersonas' query.
        /// </summary>
        /// <returns>An EntityQuery that can be loaded to retrieve <see cref="Persona"/> entity instances.</returns>
        public EntityQuery<Persona> GetPersonasQuery()
        {
            this.ValidateMethod("GetPersonasQuery", null);
            return base.CreateQuery<Persona>("GetPersonas", null, false, true);
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new PersonaContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'PersonaService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IPersonaServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetPersonas' operation.
            /// </summary>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/PersonaService/GetPersonasDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/PersonaService/GetPersonas", ReplyAction="http://tempuri.org/PersonaService/GetPersonasResponse")]
            [WebGet()]
            IAsyncResult BeginGetPersonas(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetPersonas'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetPersonas'.</param>
            /// <returns>The 'QueryResult' returned from the 'GetPersonas' operation.</returns>
            QueryResult<Persona> EndGetPersonas(IAsyncResult result);
            
            /// <summary>
            /// Asynchronously invokes the 'SubmitChanges' operation.
            /// </summary>
            /// <param name="changeSet">The change-set to submit.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/PersonaService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/PersonaService/SubmitChanges", ReplyAction="http://tempuri.org/PersonaService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginSubmitChanges'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginSubmitChanges'.</param>
            /// <returns>The collection of change-set entry elements returned from 'SubmitChanges'.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class PersonaContextEntityContainer : EntityContainer
        {
            
            public PersonaContextEntityContainer()
            {
                this.CreateEntitySet<Persona>(EntitySetOperations.All);
            }
        }
    }
}
