//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace BigFiveQ.Controls.ExamenBfqService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pregunta", Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Services")]
    public partial class Pregunta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IndexField;
        
        private string StatementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statement {
            get {
                return this.StatementField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementField, value) != true)) {
                    this.StatementField = value;
                    this.RaisePropertyChanged("Statement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Services")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string StatementField;
        
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statement {
            get {
                return this.StatementField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementField, value) != true)) {
                    this.StatementField = value;
                    this.RaisePropertyChanged("Statement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Examen", Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Services")]
    public partial class Examen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> PreguntasField;
        
        private System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> RespuestasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> Preguntas {
            get {
                return this.PreguntasField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntasField, value) != true)) {
                    this.PreguntasField = value;
                    this.RaisePropertyChanged("Preguntas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> Respuestas {
            get {
                return this.RespuestasField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestasField, value) != true)) {
                    this.RespuestasField = value;
                    this.RaisePropertyChanged("Respuestas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contestacion", Namespace="http://schemas.datacontract.org/2004/07/BigFiveQAdmin.Web.Services")]
    public partial class Contestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int NumeroPreguntaField;
        
        private int RepuestaSeleccionadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPregunta {
            get {
                return this.NumeroPreguntaField;
            }
            set {
                if ((this.NumeroPreguntaField.Equals(value) != true)) {
                    this.NumeroPreguntaField = value;
                    this.RaisePropertyChanged("NumeroPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepuestaSeleccionada {
            get {
                return this.RepuestaSeleccionadaField;
            }
            set {
                if ((this.RepuestaSeleccionadaField.Equals(value) != true)) {
                    this.RepuestaSeleccionadaField = value;
                    this.RaisePropertyChanged("RepuestaSeleccionada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ExamenBfqService.ExamenBfqService")]
    public interface ExamenBfqService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ExamenBfqService/GetAllPreguntas", ReplyAction="urn:ExamenBfqService/GetAllPreguntasResponse")]
        System.IAsyncResult BeginGetAllPreguntas(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> EndGetAllPreguntas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ExamenBfqService/GetAllRespuestas", ReplyAction="urn:ExamenBfqService/GetAllRespuestasResponse")]
        System.IAsyncResult BeginGetAllRespuestas(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> EndGetAllRespuestas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ExamenBfqService/GetExamen", ReplyAction="urn:ExamenBfqService/GetExamenResponse")]
        System.IAsyncResult BeginGetExamen(System.AsyncCallback callback, object asyncState);
        
        BigFiveQ.Controls.ExamenBfqService.Examen EndGetExamen(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ExamenBfqService/CommitExamen", ReplyAction="urn:ExamenBfqService/CommitExamenResponse")]
        System.IAsyncResult BeginCommitExamen(System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones, string userName, System.AsyncCallback callback, object asyncState);
        
        string EndCommitExamen(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExamenBfqServiceChannel : BigFiveQ.Controls.ExamenBfqService.ExamenBfqService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllPreguntasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllPreguntasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllRespuestasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllRespuestasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public BigFiveQ.Controls.ExamenBfqService.Examen Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((BigFiveQ.Controls.ExamenBfqService.Examen)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommitExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CommitExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamenBfqServiceClient : System.ServiceModel.ClientBase<BigFiveQ.Controls.ExamenBfqService.ExamenBfqService>, BigFiveQ.Controls.ExamenBfqService.ExamenBfqService {
        
        private BeginOperationDelegate onBeginGetAllPreguntasDelegate;
        
        private EndOperationDelegate onEndGetAllPreguntasDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllPreguntasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllRespuestasDelegate;
        
        private EndOperationDelegate onEndGetAllRespuestasDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllRespuestasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetExamenDelegate;
        
        private EndOperationDelegate onEndGetExamenDelegate;
        
        private System.Threading.SendOrPostCallback onGetExamenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCommitExamenDelegate;
        
        private EndOperationDelegate onEndCommitExamenDelegate;
        
        private System.Threading.SendOrPostCallback onCommitExamenCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ExamenBfqServiceClient() {
        }
        
        public ExamenBfqServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamenBfqServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenBfqServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamenBfqServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllPreguntasCompletedEventArgs> GetAllPreguntasCompleted;
        
        public event System.EventHandler<GetAllRespuestasCompletedEventArgs> GetAllRespuestasCompleted;
        
        public event System.EventHandler<GetExamenCompletedEventArgs> GetExamenCompleted;
        
        public event System.EventHandler<CommitExamenCompletedEventArgs> CommitExamenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.BeginGetAllPreguntas(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllPreguntas(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.EndGetAllPreguntas(System.IAsyncResult result) {
            return base.Channel.EndGetAllPreguntas(result);
        }
        
        private System.IAsyncResult OnBeginGetAllPreguntas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).BeginGetAllPreguntas(callback, asyncState);
        }
        
        private object[] OnEndGetAllPreguntas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> retVal = ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).EndGetAllPreguntas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllPreguntasCompleted(object state) {
            if ((this.GetAllPreguntasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllPreguntasCompleted(this, new GetAllPreguntasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllPreguntasAsync() {
            this.GetAllPreguntasAsync(null);
        }
        
        public void GetAllPreguntasAsync(object userState) {
            if ((this.onBeginGetAllPreguntasDelegate == null)) {
                this.onBeginGetAllPreguntasDelegate = new BeginOperationDelegate(this.OnBeginGetAllPreguntas);
            }
            if ((this.onEndGetAllPreguntasDelegate == null)) {
                this.onEndGetAllPreguntasDelegate = new EndOperationDelegate(this.OnEndGetAllPreguntas);
            }
            if ((this.onGetAllPreguntasCompletedDelegate == null)) {
                this.onGetAllPreguntasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllPreguntasCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllPreguntasDelegate, null, this.onEndGetAllPreguntasDelegate, this.onGetAllPreguntasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.BeginGetAllRespuestas(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllRespuestas(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.EndGetAllRespuestas(System.IAsyncResult result) {
            return base.Channel.EndGetAllRespuestas(result);
        }
        
        private System.IAsyncResult OnBeginGetAllRespuestas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).BeginGetAllRespuestas(callback, asyncState);
        }
        
        private object[] OnEndGetAllRespuestas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> retVal = ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).EndGetAllRespuestas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllRespuestasCompleted(object state) {
            if ((this.GetAllRespuestasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllRespuestasCompleted(this, new GetAllRespuestasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllRespuestasAsync() {
            this.GetAllRespuestasAsync(null);
        }
        
        public void GetAllRespuestasAsync(object userState) {
            if ((this.onBeginGetAllRespuestasDelegate == null)) {
                this.onBeginGetAllRespuestasDelegate = new BeginOperationDelegate(this.OnBeginGetAllRespuestas);
            }
            if ((this.onEndGetAllRespuestasDelegate == null)) {
                this.onEndGetAllRespuestasDelegate = new EndOperationDelegate(this.OnEndGetAllRespuestas);
            }
            if ((this.onGetAllRespuestasCompletedDelegate == null)) {
                this.onGetAllRespuestasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllRespuestasCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllRespuestasDelegate, null, this.onEndGetAllRespuestasDelegate, this.onGetAllRespuestasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.BeginGetExamen(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetExamen(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BigFiveQ.Controls.ExamenBfqService.Examen BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.EndGetExamen(System.IAsyncResult result) {
            return base.Channel.EndGetExamen(result);
        }
        
        private System.IAsyncResult OnBeginGetExamen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).BeginGetExamen(callback, asyncState);
        }
        
        private object[] OnEndGetExamen(System.IAsyncResult result) {
            BigFiveQ.Controls.ExamenBfqService.Examen retVal = ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).EndGetExamen(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetExamenCompleted(object state) {
            if ((this.GetExamenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetExamenCompleted(this, new GetExamenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetExamenAsync() {
            this.GetExamenAsync(null);
        }
        
        public void GetExamenAsync(object userState) {
            if ((this.onBeginGetExamenDelegate == null)) {
                this.onBeginGetExamenDelegate = new BeginOperationDelegate(this.OnBeginGetExamen);
            }
            if ((this.onEndGetExamenDelegate == null)) {
                this.onEndGetExamenDelegate = new EndOperationDelegate(this.OnEndGetExamen);
            }
            if ((this.onGetExamenCompletedDelegate == null)) {
                this.onGetExamenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetExamenCompleted);
            }
            base.InvokeAsync(this.onBeginGetExamenDelegate, null, this.onEndGetExamenDelegate, this.onGetExamenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.BeginCommitExamen(System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones, string userName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCommitExamen(contestaciones, userName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string BigFiveQ.Controls.ExamenBfqService.ExamenBfqService.EndCommitExamen(System.IAsyncResult result) {
            return base.Channel.EndCommitExamen(result);
        }
        
        private System.IAsyncResult OnBeginCommitExamen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones = ((System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion>)(inValues[0]));
            string userName = ((string)(inValues[1]));
            return ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).BeginCommitExamen(contestaciones, userName, callback, asyncState);
        }
        
        private object[] OnEndCommitExamen(System.IAsyncResult result) {
            string retVal = ((BigFiveQ.Controls.ExamenBfqService.ExamenBfqService)(this)).EndCommitExamen(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCommitExamenCompleted(object state) {
            if ((this.CommitExamenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CommitExamenCompleted(this, new CommitExamenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CommitExamenAsync(System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones, string userName) {
            this.CommitExamenAsync(contestaciones, userName, null);
        }
        
        public void CommitExamenAsync(System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones, string userName, object userState) {
            if ((this.onBeginCommitExamenDelegate == null)) {
                this.onBeginCommitExamenDelegate = new BeginOperationDelegate(this.OnBeginCommitExamen);
            }
            if ((this.onEndCommitExamenDelegate == null)) {
                this.onEndCommitExamenDelegate = new EndOperationDelegate(this.OnEndCommitExamen);
            }
            if ((this.onCommitExamenCompletedDelegate == null)) {
                this.onCommitExamenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCommitExamenCompleted);
            }
            base.InvokeAsync(this.onBeginCommitExamenDelegate, new object[] {
                        contestaciones,
                        userName}, this.onEndCommitExamenDelegate, this.onCommitExamenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BigFiveQ.Controls.ExamenBfqService.ExamenBfqService CreateChannel() {
            return new ExamenBfqServiceClientChannel(this);
        }
        
        private class ExamenBfqServiceClientChannel : ChannelBase<BigFiveQ.Controls.ExamenBfqService.ExamenBfqService>, BigFiveQ.Controls.ExamenBfqService.ExamenBfqService {
            
            public ExamenBfqServiceClientChannel(System.ServiceModel.ClientBase<BigFiveQ.Controls.ExamenBfqService.ExamenBfqService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllPreguntas(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllPreguntas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> EndGetAllPreguntas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta> _result = ((System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Pregunta>)(base.EndInvoke("GetAllPreguntas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllRespuestas(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllRespuestas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> EndGetAllRespuestas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta> _result = ((System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Respuesta>)(base.EndInvoke("GetAllRespuestas", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetExamen(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetExamen", _args, callback, asyncState);
                return _result;
            }
            
            public BigFiveQ.Controls.ExamenBfqService.Examen EndGetExamen(System.IAsyncResult result) {
                object[] _args = new object[0];
                BigFiveQ.Controls.ExamenBfqService.Examen _result = ((BigFiveQ.Controls.ExamenBfqService.Examen)(base.EndInvoke("GetExamen", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCommitExamen(System.Collections.ObjectModel.ObservableCollection<BigFiveQ.Controls.ExamenBfqService.Contestacion> contestaciones, string userName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = contestaciones;
                _args[1] = userName;
                System.IAsyncResult _result = base.BeginInvoke("CommitExamen", _args, callback, asyncState);
                return _result;
            }
            
            public string EndCommitExamen(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("CommitExamen", _args, result)));
                return _result;
            }
        }
    }
}
